---
- name: prepare docker container for tasks
  hosts: localhost
  gather_facts: no
  sudo: True
  tasks:
    - name: enshure docker ansible client image is present
      docker_image:
        name: docker_ansible_client
        path: docker_ansible_client
        state: present

    - name: create client container
      docker:
        image: docker_ansible_client
        name: ansible_client
        detach: False
        expose: 80
        ports:
        - "8080:80"
        state: running

    - name: add container to the hosts inventory
      add_host:
        hostname: "{{ item.Name }}"
        groups: docker
        ansible_ssh_host: "{{ item.NetworkSettings.IPAddress }}"
        ansible_ssh_port: 22
      when: item.State.Running == True
      with_items: docker_containers

- name: run user tasks in the client container
  hosts: docker
  remote_user: root
  tasks:
    - name: include container tasks
      include: container_tasks/tasks.yml
